server:
  applicationConnectors:
    - type: http
      port: 5000
  adminConnectors:
    - type: http
      port: 5001

db:
  driverClass: org.postgresql.Driver
  user: superset
  password: superset
  url: jdbc:postgresql://postgres:5432/marquez